[versions]
accompanist = "0.24.12-rc"
activity-compose = "1.4.0"
agp = "7.2.1"
app-compat = "1.4.2"
apollo = "3.3.2"
coil-compose = "2.1.0"
compose = "1.2.0-rc02"
compose-material3 = "1.0.0-alpha13"
compose-preferences = "0.1.4"
core-ktx = "1.8.0"
core-splashscreen = "1.0.0-rc01"
coroutines = "1.6.3"
dagger-hilt = "2.42"
dagger-hilt-extensions = "1.0.0"
dagger-hilt-navigation-compose = "1.0.0"
dagger-hilt-vm-compiler = "1.0.0"
datastore = "1.0.0"
detekt = "1.20.0"
firebase-auth-ktx = "21.0.6"
google-services = "4.3.10"
kotlin = "1.6.21"
ktlint = "10.3.0"
leakcanary = "2.9.1"
lifecycle = "2.4.1"
material = "1.6.1"
moshi = "1.13.0"
navigation_compose = "2.5.0-rc02"
orbit = "4.3.2"
paging = "3.1.1"
paging_compose = "1.0.0-alpha15"
room = "2.4.2"
spotless = "6.7.2"
timber = "5.0.1"
timeago = "4.0.3"
tink = "1.6.1"
versions = "0.42.0"
wire = "4.4.0"
work = "2.7.1"

[libraries]
accompanist-navigation_animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-system-ui-controller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
app-compat = { module = "androidx.appcompat:appcompat", version.ref = "app-compat" }
apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-preferences = { module = "com.github.Sh4dowSoul:ComposePreferences", version.ref = "compose-preferences" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "dagger-hilt-extensions" }
dagger-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "dagger-hilt-navigation-compose" }
dagger-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "dagger-hilt-extensions" }
datastore-prefs = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-proto = { module = "androidx.datastore:datastore", version.ref = "datastore" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebase-auth-ktx" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
navigation_compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation_compose" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit" }
orbit-vm = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }
paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
timeago = { module = "com.github.marlonlom:timeago", version.ref = "timeago" }
tink = { module = "com.google.crypto.tink:tink-android", version.ref = "tink" }
wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

[bundles]
implementation = [
    "accompanist-navigation_animation",
    "accompanist-placeholder",
    "accompanist-system-ui-controller",
    "activity-compose",
    "app-compat",
    "apollo-runtime",
    "coil-compose",
    "compose-animation",
    "compose-material",
    "compose-material3",
    "compose-preferences",
    "compose-ui",
    "compose-ui-tooling",
    "core-ktx",
    "core-splashscreen",
    "coroutines-android",
    "coroutines-play-services",
    "dagger-hilt-android",
    "dagger-hilt-navigation-compose",
    "dagger-hilt-work",
    "datastore-prefs",
    "datastore-proto",
    "firebase-auth-ktx",
    "kotlin-stdlib",
    "lifecycle-runtime-ktx",
    "material",
    "material-icons-extended",
    "moshi",
    "navigation_compose",
    "orbit-compose",
    "orbit-vm",
    "paging-compose",
    "paging-runtime-ktx",
    "room-ktx",
    "room-paging",
    "room-runtime",
    "timber",
    "timeago",
    "tink",
    "work-runtime-ktx"
]
kapt = [
    "dagger-hilt-android-compiler",
    "dagger-hilt-compiler",
    "room-compiler"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
wire = { id = "com.squareup.wire", version.ref = "wire" }
